--Obtener los 5 premios mas recientes
SELECT * FROM (SELECT PRIZE_NAME, PRIZE_DATE, ROW_NUMBER() OVER (ORDER BY PRIZE_DATE DESC)AS RECIENTES
    FROM LESLIE.PRIZE)
where RECIENTES <6;

--obtener los ultimos 10 premios de fisica
SELECT * FROM (SELECT PRIZE_NAME, PRICE_DATE, CATEGORY_PRIZE, ROW_NUMBER() OVER (ORDER BY PRIZE_DATE DESC)AS RECIENTES
FROM LESLIE.PRIZE 
INNER JOIN LESLIE.CATEGORY CT
ON LESLIE.CATEGORY.CATEGORY_ID = LESLIE.PRIZE.CATEGORY_ID
WHERE CT.CATEGORY_PRIZE = 'FISICA')
WHERE RECIENTES<11;

--obtener las personas que han ganado mas de un premio
SELECT * FROM (SELECT WINNER_ID, COUNT (WINNER_ID) AS GANADOS
FROM LESLIE.WINNERS
GROUP BY WINNER_ID)
WHERE GANADOS > 1;

--obtener el campo o lenguaje con mas premios 
SELECT FIELD, AF.GANADOS
  FROM (SELECT FIELD_ID,
               GANADOS,
               ROW_NUMBER () OVER (ORDER BY GANADOS DESC) AS ORDEN
          FROM (  SELECT FIELD_ID, COUNT (FIELD_ID) AS GANADOS
                    FROM LESLIE.PRIZE_FIELD
                GROUP BY FIELD_ID
                ORDER BY FIELD_ID DESC)) AF
       INNER JOIN LESLIE.FIELD ON LESLIE.FIELD.FIELD_ID = AF.FIELD_ID
 WHERE AF.ORDEN = 1;

--Obtener los premios ganados desde 1980 a 1990 en quimica 
SELECT PRIZE_NAME,PRIZE_DATE, CATEGORY_PRIZE
FROM LESLIE.PRIZE
INNER JOIN LESLIE.CATEGORY ON LESLIE.CATEGORY.CATEGORY_ID = LESLIE.PRIZE.CATEGORY_ID
WHERE CATEGORY_PRIZE = 'quimica' AND PRIZE_DATE BETWEEN '01/01/1980' AND '31/12/1990';

--Obtener el premio nobel ganado en menos ocasiones
SELECT PRIZE_NAME, GANADOS
FROM(SELECT PRIZE_NAME, GANADOS, ROW_NUMBER() OVER (ORDER BY GANADOS ASC) AS MG
FROM (SELECT PRIZE_NAME, COUNT(PRIZE_NAME) AS GANADOS
FROM LESLIE.PRIZE GROUP BY PRIZE_NAME))
WHERE MG =1;

--Obtener el pais con mas premios
SELECT COUNTRY, ORDEN.GANADOS
  FROM (SELECT COUNTRY_ID,
               GANADOS,
               ROW_NUMBER () OVER (ORDER BY GANADOS DESC) AS MG
          FROM (  SELECT COUNTRY_ID, COUNT (COUNTRY_ID) AS GANADOS
                    FROM LESLIE.PRIZE
                GROUP BY COUNTRY_ID
                ORDER BY GANADOS DESC)) ORDEN
       INNER JOIN LESLIE.COUNTRY ON LESLIE.COUNTRY.COUNTRY_ID = ORDEN.COUNTRY_ID
 WHERE MG = 1;
 
 --Obtener los premios nobel compartido
   SELECT LESLIE.PRIZE.PRIZE_NAME,
         LESLIE.WINNERS.NAME,
         GANADORES,
         LESLIE.PRIZE.PRIZE_ID
    FROM (  SELECT PRIZE_ID, COUNT (PRIZE_ID) AS GANADORES
              FROM LESLIE.PRIZE_WINNERS
          GROUP BY PRIZE_ID
          ORDER BY GANADORES ASC) ORDEN
         INNER JOIN LESLIE.PRIZE_WINNERS 
             ON LESLIE.PRIZE-WINNERS.PRIZE_ID = ORDEN.PRIZE_ID
         INNER JOIN LESLIE.WINNERS ON LESLIE.WINNERS.WINNER_ID = LESLIE.PRIZE_WINNERS.PRIZE_ID
         INNER JOIN LESLIE.PRIZE ON LESLIE.PRIZE_WINNERS.PRIZE_ID = LESLIE.PRIZE.PRIZE_ID
   WHERE GANADORES > 1
ORDER BY LESLIE.PRIZE.PRIZE_ID ASC;
