ALTER TABLE LESLIE.ENTRADAS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LESLIE.ENTRADAS CASCADE CONSTRAINTS;

CREATE TABLE LESLIE.ENTRADAS
(
  ENTRADA_ID       INTEGER,
  MATERIAL_ID      INTEGER,
  MAQUINA_ID       INTEGER,
  MEDICION_ID      INTEGER,
  USUARIO_ID       INTEGER,
  MODIFICACION_ID  INTEGER,
  DATOS            VARCHAR2(200 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE LESLIE.MAQUINA
 DROP PRIMARY KEY CASCADE;

DROP TABLE LESLIE.MAQUINA CASCADE CONSTRAINTS;

CREATE TABLE LESLIE.MAQUINA
(
  MAQUINA_ID           INTEGER,
  DESCRIPCION_MAQUINA  VARCHAR2(200 BYTE),
  STATUS_MAQUINA       NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE LESLIE.MATERIALES
 DROP PRIMARY KEY CASCADE;

DROP TABLE LESLIE.MATERIALES CASCADE CONSTRAINTS;

CREATE TABLE LESLIE.MATERIALES
(
  MATERIAL_ID           INTEGER,
  DESCRIPCION_MATERIAL  VARCHAR2(200 BYTE),
  DIMENSION             NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE LESLIE.MEDICION
 DROP PRIMARY KEY CASCADE;

DROP TABLE LESLIE.MEDICION CASCADE CONSTRAINTS;

CREATE TABLE LESLIE.MEDICION
(
  MEDICION_ID           INTEGER,
  DESCRIPCION_MEDICION  VARCHAR2(200 BYTE),
  STATUS_MEDICION       NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE LESLIE.MODIFICACION
 DROP PRIMARY KEY CASCADE;

DROP TABLE LESLIE.MODIFICACION CASCADE CONSTRAINTS;

CREATE TABLE LESLIE.MODIFICACION
(
  MODIFICACION_ID        INTEGER,
  DESCRIPCION_PROBLEMA   VARCHAR2(200 BYTE),
  DESCRIPCION_ACTIVIDAD  VARCHAR2(200 BYTE),
  ENTRADA_ID             INTEGER,
  USUARIO_ID             INTEGER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE LESLIE.USUARIO
 DROP PRIMARY KEY CASCADE;

DROP TABLE LESLIE.USUARIO CASCADE CONSTRAINTS;

CREATE TABLE LESLIE.USUARIO
(
  USUARIO_ID  INTEGER,
  PUESTO      VARCHAR2(200 BYTE),
  NOMBRE      VARCHAR2(200 BYTE),
  APELLIDO    VARCHAR2(200 BYTE),
  TURNO       VARCHAR2(200 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX LESLIE.ENTRADAS_PK ON LESLIE.ENTRADAS
(ENTRADA_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX LESLIE.MAQUINA_PK ON LESLIE.MAQUINA
(MAQUINA_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX LESLIE.MATERIALES_PK ON LESLIE.MATERIALES
(MATERIAL_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX LESLIE.MEDICION_PK ON LESLIE.MEDICION
(MEDICION_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX LESLIE.MODIFICACION_PK ON LESLIE.MODIFICACION
(MODIFICACION_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX LESLIE.USUARIO_PK ON LESLIE.USUARIO
(USUARIO_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE LESLIE.ENTRADAS ADD (
  CONSTRAINT ENTRADAS_PK
  PRIMARY KEY
  (ENTRADA_ID)
  USING INDEX LESLIE.ENTRADAS_PK
  ENABLE VALIDATE);

ALTER TABLE LESLIE.MAQUINA ADD (
  CONSTRAINT MAQUINA_PK
  PRIMARY KEY
  (MAQUINA_ID)
  USING INDEX LESLIE.MAQUINA_PK
  ENABLE VALIDATE);

ALTER TABLE LESLIE.MATERIALES ADD (
  CONSTRAINT MATERIALES_PK
  PRIMARY KEY
  (MATERIAL_ID)
  USING INDEX LESLIE.MATERIALES_PK
  ENABLE VALIDATE);

ALTER TABLE LESLIE.MEDICION ADD (
  CONSTRAINT MEDICION_PK
  PRIMARY KEY
  (MEDICION_ID)
  USING INDEX LESLIE.MEDICION_PK
  ENABLE VALIDATE);

ALTER TABLE LESLIE.MODIFICACION ADD (
  CONSTRAINT MODIFICACION_PK
  PRIMARY KEY
  (MODIFICACION_ID)
  USING INDEX LESLIE.MODIFICACION_PK
  ENABLE VALIDATE);

ALTER TABLE LESLIE.USUARIO ADD (
  CONSTRAINT USUARIO_PK
  PRIMARY KEY
  (USUARIO_ID)
  USING INDEX LESLIE.USUARIO_PK
  ENABLE VALIDATE);

ALTER TABLE LESLIE.ENTRADAS ADD (
  CONSTRAINT ENTRADAS_R01 
  FOREIGN KEY (MATERIAL_ID) 
  REFERENCES LESLIE.MATERIALES (MATERIAL_ID)
  ENABLE VALIDATE,
  CONSTRAINT ENTRADAS_R02 
  FOREIGN KEY (MAQUINA_ID) 
  REFERENCES LESLIE.MAQUINA (MAQUINA_ID)
  ENABLE VALIDATE,
  CONSTRAINT ENTRADAS_R03 
  FOREIGN KEY (MEDICION_ID) 
  REFERENCES LESLIE.MEDICION (MEDICION_ID)
  ENABLE VALIDATE,
  CONSTRAINT ENTRADAS_R04 
  FOREIGN KEY (USUARIO_ID) 
  REFERENCES LESLIE.USUARIO (USUARIO_ID)
  ENABLE VALIDATE,
  CONSTRAINT ENTRADAS_R05 
  FOREIGN KEY (MODIFICACION_ID) 
  REFERENCES LESLIE.MODIFICACION (MODIFICACION_ID)
  ENABLE VALIDATE);
